<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mia3_search"
 *
 * Auto generated by Extension Builder 2016-05-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Search made awesome',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Marc Neuhaus',
	'author_email' => 'marc@mia3.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '9.5.0-9.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
